name: Yahoo News (JMS/Mobility Show) Scraper

on:
  workflow_dispatch:
  schedule:
    # 毎日 07:00 JST に実行（＝22:00 UTC）
    - cron: '0 22 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}   # ← ここにIDをSecrets登録
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python integrated_main.py
